/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package madarsa;
import java.io.File;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Observable;
import java.util.Observer;
/**
 *
 * @author shabbir
 */
public class AdForm extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form NewJFrame
     */
    private AdForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Insert = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textEjamaat = new javax.swing.JFormattedTextField();
        textAge = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textCell = new javax.swing.JFormattedTextField();
        Print = new javax.swing.JButton();
        textResNum = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        textAdmtFee = new javax.swing.JFormattedTextField();
        textSurName = new javax.swing.JTextField();
        labelPic = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFather = new javax.swing.JTextField();
        textStdName = new javax.swing.JTextField();
        Browse = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textSabilNum = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textAnnualFee = new javax.swing.JFormattedTextField();
        comboMonth = new javax.swing.JComboBox();
        comboYear = new javax.swing.JComboBox();
        DOADate = new javax.swing.JComboBox();
        DOAMonth = new javax.swing.JComboBox();
        DOAYear = new javax.swing.JComboBox();
        comboDate = new javax.swing.JComboBox();
        remove = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        lastRec = new javax.swing.JButton();
        nextRec = new javax.swing.JButton();
        preRec = new javax.swing.JButton();
        firstRec = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        darText = new javax.swing.JTextField();
        regText = new javax.swing.JTextField();
        mohText = new javax.swing.JTextField();
        Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("CLASS/DARAJA :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 24));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText(" SUR-NAME :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 24));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("STUDENT NAME :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 150, 24));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 255));
        jLabel16.setText("ADMISSION FORM");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 204, 38));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("FATHER NAME :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 150, 24));

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 255));
        jScrollPane1.setEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 294, 89));

        Insert.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Insert.setForeground(new java.awt.Color(0, 51, 255));
        Insert.setText("INSERT");
        getContentPane().add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 80, 40));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("CELL NUMBER :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 150, 24));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 255));
        jLabel15.setText("PICTURE : ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 215, 24));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("DATE OF ADMISSION :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 150, 24));

        textEjamaat.setForeground(new java.awt.Color(0, 0, 204));
        textEjamaat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textEjamaat.setEnabled(false);
        textEjamaat.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textEjamaat, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 99, 294, -1));

        textAge.setForeground(new java.awt.Color(0, 0, 204));
        textAge.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textAge.setEnabled(false);
        textAge.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 294, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("MOHALLA :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 150, 24));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("ADMISSION FEE :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 150, 24));

        textCell.setForeground(new java.awt.Color(0, 0, 204));
        textCell.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textCell.setEnabled(false);
        textCell.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 294, -1));

        Print.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Print.setForeground(new java.awt.Color(0, 51, 255));
        Print.setText("PRINT");
        getContentPane().add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 100, 40));

        textResNum.setForeground(new java.awt.Color(0, 0, 204));
        textResNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textResNum.setEnabled(false);
        textResNum.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textResNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 294, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("REGISTRATTION ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 150, 24));

        textAdmtFee.setForeground(new java.awt.Color(0, 0, 204));
        textAdmtFee.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textAdmtFee.setEnabled(false);
        textAdmtFee.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textAdmtFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 300, -1));

        textSurName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        textSurName.setForeground(new java.awt.Color(0, 51, 255));
        textSurName.setEnabled(false);
        textSurName.setName(""); // NOI18N
        getContentPane().add(textSurName, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 192, 294, -1));
        textSurName.getAccessibleContext().setAccessibleName("");

        labelPic.setBackground(new java.awt.Color(179, 171, 165));
        labelPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/madarsa/24483_152146_HBI-24483.jpg"))); // NOI18N
        labelPic.setText("Add picture");
        labelPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPic.setEnabled(false);
        getContentPane().add(labelPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 103, 140));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("RESIDENCE NUMBER :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 150, 24));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 255));
        jLabel13.setText("ADDRESS :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 150, 24));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("EJAMAAT ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 150, 24));

        textFather.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        textFather.setForeground(new java.awt.Color(0, 51, 255));
        textFather.setEnabled(false);
        getContentPane().add(textFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 161, 294, -1));

        textStdName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        textStdName.setForeground(new java.awt.Color(0, 51, 255));
        textStdName.setEnabled(false);
        getContentPane().add(textStdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 130, 294, -1));

        Browse.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Browse.setForeground(new java.awt.Color(0, 51, 255));
        Browse.setText("BROWSE");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });
        getContentPane().add(Browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("AGE :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 150, 24));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText(" Date Of Birth :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, 24));

        textSabilNum.setForeground(new java.awt.Color(0, 0, 204));
        textSabilNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textSabilNum.setEnabled(false);
        textSabilNum.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textSabilNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 294, -1));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 255));
        jLabel18.setText("SABIL NUMBER :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 150, 24));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 255));
        jLabel19.setText("ANNUAL FEE :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 150, 24));

        textAnnualFee.setForeground(new java.awt.Color(0, 0, 204));
        textAnnualFee.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textAnnualFee.setEnabled(false);
        textAnnualFee.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(textAnnualFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 300, -1));

        comboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        comboMonth.setEnabled(false);
        getContentPane().add(comboMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 160, -1));

        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        comboYear.setEnabled(false);
        getContentPane().add(comboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        DOADate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        DOADate.setEnabled(false);
        getContentPane().add(DOADate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        DOAMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        DOAMonth.setEnabled(false);
        getContentPane().add(DOAMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 170, -1));

        DOAYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        DOAYear.setEnabled(false);
        getContentPane().add(DOAYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        comboDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        comboDate.setEnabled(false);
        getContentPane().add(comboDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        remove.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        remove.setForeground(new java.awt.Color(0, 51, 255));
        remove.setText("REMOVE");
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 80, 40));

        submit.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 51, 255));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 80, 40));

        edit.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        edit.setForeground(new java.awt.Color(0, 51, 255));
        edit.setText("EDIT");
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 80, 40));

        lastRec.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lastRec.setForeground(new java.awt.Color(0, 51, 255));
        lastRec.setText("->>");
        getContentPane().add(lastRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 60, 40));

        nextRec.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nextRec.setForeground(new java.awt.Color(0, 51, 255));
        nextRec.setText("->");
        getContentPane().add(nextRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, 60, 40));

        preRec.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        preRec.setForeground(new java.awt.Color(0, 51, 255));
        preRec.setText("<-");
        getContentPane().add(preRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 60, 40));

        firstRec.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        firstRec.setForeground(new java.awt.Color(0, 51, 255));
        firstRec.setText("<<-");
        getContentPane().add(firstRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 60, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 770, 0));

        darText.setEnabled(false);
        getContentPane().add(darText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 290, -1));

        regText.setEnabled(false);
        getContentPane().add(regText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 290, -1));

        mohText.setEnabled(false);
        getContentPane().add(mohText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 290, -1));

        Close.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Close.setForeground(new java.awt.Color(0, 51, 255));
        Close.setText("BACK TO WELCOME PAGE");
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //it is invoked when the clear all button is pressed it initializes all the textfields 
    protected void newForm(){
    jTextArea1.setEnabled(true);

    textAdmtFee.setEnabled(true);
    textAge.setEnabled(true);
    textAnnualFee.setEnabled(true);
    textCell.setEnabled(true);
    textEjamaat.setEnabled(true);
    textFather.setEnabled(true);
 //   textRegId.setText("");
    textResNum.setEnabled(true);
    textSabilNum.setEnabled(true);
    textStdName.setEnabled(true);
    textSurName.setEnabled(true);
    labelPic.setEnabled(true);
    comboDate.setEnabled(true);
    comboMonth.setEnabled(true);
    comboYear.setEnabled(true);
    DOADate.setEnabled(true);
    DOAMonth.setEnabled(true);
    DOAYear.setEnabled(true);
        jTextArea1.setEnabled(true);    
    


}
    
    protected void setDefaultData(String[] data){
        jTextArea1.setText("");
    labelPic.setText("addPicture");
    textAdmtFee.setText("");
    textAge.setText("");
    textAnnualFee.setText("");
    textCell.setText("");
    textEjamaat.setText("");
    textFather.setText("");
    regText.setText(data[0]);
    darText.setText(data[1]);
    mohText.setText(data[2]);
    textResNum.setText("");
    textSabilNum.setText("");
    textStdName.setText("");
    textSurName.setText("");
    labelPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
    
    }
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

 //       DarMoh[0] = ComboDar.getSelectedItem().toString();
//DarMoh[1] = ComboMoh.getSelectedItem().toString();


// TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        Picture pic = Picture.getInstance("AdForm");
        pic.addObserver(this);

        // TODO add your handling code here:
    }//GEN-LAST:event_BrowseActionPerformed
protected void recAccess(){
    jTextArea1.setEnabled(false);

    textAdmtFee.setEnabled(false);
    textAge.setEnabled(false);
    textAnnualFee.setEnabled(false);
    textCell.setEnabled(false);
    textEjamaat.setEnabled(false);
    textFather.setEnabled(false);
 //   textRegId.setText("");
    textResNum.setEnabled(false);
    textSabilNum.setEnabled(false);
    textStdName.setEnabled(false);
    textSurName.setEnabled(false);
    labelPic.setEnabled(false);
    comboDate.setEnabled(false);
    comboMonth.setEnabled(false);
    comboYear.setEnabled(false);
    DOADate.setEnabled(false);
    DOAMonth.setEnabled(false);
    DOAYear.setEnabled(false);
        jTextArea1.setEnabled(false);

}
 

    
    //set value in the AdForm
protected void getTableValue(String[] data){
char[] c = new char[12];
    
darText.setText(data[0]);
regText.setText(data[1]);
textEjamaat.setText(data[2]);
textStdName.setText(data[3]);
textFather.setText(data[4]);
textSurName.setText(data[5]);
textSabilNum.setText(data[6]);

textAge.setText(data[8]);
textResNum.setText(data[9]);
textCell.setText(data[10]);
mohText.setText(data[11]);
jTextArea1.setText(data[12]);

textAdmtFee.setText(data[14]);
textAnnualFee.setText(data[15]);
lastRecord = Integer.parseInt(data[17]);

System.out.println(data[7].charAt(0));
comboDate.setSelectedItem(data[7].charAt(0));
comboMonth.setSelectedItem(data[7].charAt(3)+data[7].charAt(4));

comboYear.setSelectedItem(data[7].charAt(6)+data[7].charAt(7));


}


protected void insertOp(){
//in invoked when the insert button is pressed takes all the values fro the text field in String format
    bioData[0] = darText.getText();    
    bioData[1] = regText.getText();
        bioData[2] = textEjamaat.getText();
 //   bioData[1] = labelPic.getIcon().toString();
  // System.out.println(bioData[1] + "label pic ");
    bioData[3] = textStdName.getText();
    bioData[4] =textFather.getText();
    bioData[5] =textSurName.getText();
    bioData[6] =textSabilNum.getText();

    bioData[8] =textAge.getText() ;
    bioData[9] = textResNum.getText() ;
    bioData[10] = textCell.getText(); 
    bioData[11] = mohText.getText();
    bioData[12] = jTextArea1.getText().toString();

    bioData[14] = textAdmtFee.getText();
    bioData[15] = textAnnualFee.getText();
    bioData[16] = "picture text";
    String month = comboMonth.getSelectedItem().toString() ;
    bioData[7] =comboDate.getSelectedItem().toString()+"\\"+ month.substring(0,3)+"\\"+comboYear.getSelectedItem().toString() ;
    
      String DOA = DOAMonth.getSelectedItem().toString() ;
    bioData[13] =DOADate.getSelectedItem().toString()+"\\"+ month.substring(0,3)+"\\"+DOAYear.getSelectedItem().toString() ;

//newForm();
}
//sets the value of registrationId field by calculating it from the daraja value
    protected void regId(String value){

//textRegId.setText(value);
}
//insert the picture in the picture icon
protected void picture(String value){

    labelPic.setText("");
    labelPic.setIcon(new javax.swing.ImageIcon(getClass().getResource(value)));
   
}

//setting combo box default values
protected void setDefault(String[][] str){


    variable[0] = comboDate;
    variable[1] = comboMonth;
    variable[2] = comboYear;
    variable[3] = DOADate;
    variable[4] = DOAMonth;
    variable[5] = DOAYear;
    int num = 0,comboNum = 0;

while(comboNum < variable.length)
{
    
    if(num<3)
    {
        setCombo1(str[num+2],variable[comboNum]);
        comboNum++;
        num++;
    }
    else 
        num = 0;
}

}

//
//sets values of each combo
protected void setCombo1(String[] str,javax.swing.JComboBox variable)
{
int num = 0;
variable.removeAllItems();

while(num < str.length)
{
variable.addItem(str[num]);
num++;
}
}

public void setPic(){

    labelPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/shabbir/Documents/Image0274.jpg")));
}

    void addEditListener(java.awt.event.ActionListener evt){
    
edit.addActionListener(evt);}    

    void addSubmitListener(java.awt.event.ActionListener evt){
    
submit.addActionListener(evt);}
    void addRemoveListener(java.awt.event.ActionListener evt){
    
remove.addActionListener(evt);}
    
    void addInsertListener(java.awt.event.ActionListener evt){
    
Insert.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}
void addPrintListener(java.awt.event.ActionListener evt){
    
Print.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}

void addBrowseListener(java.awt.event.ActionListener evt){
    
//Browse.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}
    void addNextRecListener(java.awt.event.ActionListener evt){
    
nextRec.addActionListener(evt);}
    
    void addPreRecListener(java.awt.event.ActionListener evt){
    
preRec.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}
void addFirstRecListener(java.awt.event.ActionListener evt){
    
firstRec.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}

void addLastRecListener(java.awt.event.ActionListener evt){
    
lastRec.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}
public void addCloseListener(java.awt.event.ActionListener evt){
    instance = null;
    Close.addActionListener(evt);

}


protected void setjFormattedTextField1(String sYear)//it gives the year 
{
//jFormattedTextField1.setText(sYear + "00");
}
  public static AdForm getInstance() {
            if(instance == null) {
         instance = new AdForm();
      }
    return instance;
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    t = Thread.currentThread();
                       madarsa.AdFormController view = AdFormController.getInstance() ;
                       
                // new madarsa.AdFormController();
            }
        });
    }
    static int lastRecord = 0;
    String bioData[] = new String[18],DarMoh[];
static Thread t;    
private static AdForm instance = null;
private javax.swing.JComboBox variable[] = new javax.swing.JComboBox[6];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JButton Close;
    private javax.swing.JComboBox DOADate;
    private javax.swing.JComboBox DOAMonth;
    private javax.swing.JComboBox DOAYear;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Print;
    private javax.swing.JComboBox comboDate;
    private javax.swing.JComboBox comboMonth;
    private javax.swing.JComboBox comboYear;
    private javax.swing.JTextField darText;
    private javax.swing.JButton edit;
    private javax.swing.JButton firstRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelPic;
    private javax.swing.JButton lastRec;
    private javax.swing.JTextField mohText;
    private javax.swing.JButton nextRec;
    private javax.swing.JButton preRec;
    private javax.swing.JTextField regText;
    private javax.swing.JButton remove;
    private javax.swing.JButton submit;
    private javax.swing.JFormattedTextField textAdmtFee;
    private javax.swing.JFormattedTextField textAge;
    private javax.swing.JFormattedTextField textAnnualFee;
    private javax.swing.JFormattedTextField textCell;
    private javax.swing.JFormattedTextField textEjamaat;
    private javax.swing.JTextField textFather;
    private javax.swing.JFormattedTextField textResNum;
    private javax.swing.JFormattedTextField textSabilNum;
    private javax.swing.JTextField textStdName;
    private javax.swing.JTextField textSurName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if(arg instanceof String)
        {
        String pic =(String)arg;
            labelPic.setIcon(new javax.swing.ImageIcon(getClass().getResource(pic)));
      //  labelPic.setIcon(createImageIcon(pic));
        }
        }
}
