/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package madarsa;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author shabbir
 */
public class ChallanDetails extends javax.swing.JFrame {

    /**
     * Creates new form ChallanDetails
     */
    private static ChallanDetails instance = null;
     public static ChallanDetails getInstance() {
      if(instance == null) {
         instance = new ChallanDetails();
      }
    return instance;
  } 
     
    public ChallanDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        search = new javax.swing.JButton();
        comboDar = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PChallan = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        comboMoh = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        jSeparator6.setForeground(new java.awt.Color(0, 0, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setForeground(new java.awt.Color(0, 0, 204));
        search.setText("SEARCH");
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 110, 60));

        comboDar.setForeground(new java.awt.Color(0, 0, 204));
        comboDar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));
        getContentPane().add(comboDar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 174, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("SEARCH BY DARAJA :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 20));

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 204));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jScrollPane1.setMaximumSize(new java.awt.Dimension(2100000000, 1800));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(2100000000, 1800));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CHALLAN", "REG ID", "NAME", "MONTH-NAME", "TUTION-FEE", "REG-FEE", "EXAM-FEE", "ENROLLMENT", "ARREARS", "PENALTY", "TOTAL", "DUE-DATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setMaximumSize(new java.awt.Dimension(2000000000, 200000));
        jTable1.setMinimumSize(new java.awt.Dimension(1800, 1800));
        jTable1.setPreferredSize(new java.awt.Dimension(2000000000, 200000));
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(5).setResizable(false);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(6).setResizable(false);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(7).setResizable(false);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(8).setResizable(false);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(9).setResizable(false);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(10).setResizable(false);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(11).setResizable(false);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(60);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1300, 600));

        PChallan.setForeground(new java.awt.Color(0, 0, 204));
        PChallan.setText("PRINT CHALLAN FORM");
        PChallan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PChallanActionPerformed(evt);
            }
        });
        getContentPane().add(PChallan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 200, 30));

        print.setForeground(new java.awt.Color(0, 0, 204));
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("STUDENT FEE STATUS");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 38));

        back.setForeground(new java.awt.Color(0, 0, 204));
        back.setText("BACK TO WELCOME PAGE");
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 12, -1, -1));

        comboMoh.setForeground(new java.awt.Color(0, 0, 204));
        comboMoh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));
        getContentPane().add(comboMoh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 174, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("SEARCH BY MOHALLA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PChallanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PChallanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PChallanActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed

        instance.printComponents(null);
        //PrintUIWindow printing = new PrintUIWindow(this);
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed
void searchListener(java.awt.event.ActionListener evt){
    
search.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}
void printListener(java.awt.event.ActionListener evt){
    
print.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}
void printChallanListener(java.awt.event.ActionListener evt){

PChallan.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}
void backListener(java.awt.event.ActionListener evt){
    
back.addActionListener(evt);
//adding a listener whose value will be given in the controller class
}

protected void setDefault(String[][] str,int totalStd){
String value  = Integer.toString(totalStd);
//setting combo box default values


//value = totalStd.toString();
//searchDar.setText(value);
setCombo1(str[0]);
setCombo2(str[1]);

}
protected void setCombo1(String[] str)
{
int num = 0;
while(num < str.length)
{
comboDar.addItem(str[num]);
num++;
}
}
protected void setCombo2(String[] str)
{
int num = 0;
while(num < str.length)
{
comboMoh.addItem(str[num]);
num++;
}
}
protected  void setTotals(int totalRecords)
{
//txtTotalStdDar.setText(Integer.toString(totalRecords));
//set total students 3 fields
}

protected String[] getVerification(){
//firstly get the value of daraja and mohalla as it should not be null
comboDarValue[0] = comboDar.getSelectedItem().toString(); 
comboDarValue[1] = comboMoh.getSelectedItem().toString(); 
return comboDarValue;
}
//get the value of first row from the table
protected String[] getTableData(){
String[] tableData = new String[18]; 


for(int count = 0;count<jTable1.getColumnCount();count++)
    tableData[count] = (String) jTable1.getValueAt(rowCounter,count);
//System.out.println("in AllStdData"+tableData[0]);   
rowCounter++;

return tableData;

}

protected void removeRow(){

counter = 0;
}

protected void setTableData(String data[][])
{
//set data in the table
int arrayList = 0;
Calendar cal = new GregorianCalendar();
int    yearCalc = cal.get(Calendar.MONTH);

while(data[arrayList]!= null){     
for(int num = 0;num< jTable1.getColumnCount()  ;num++)
{
    jTable1.setValueAt(data[arrayList][num], counter, num);
}
counter++;
arrayList++;
}
   
}
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChallanDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChallanDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChallanDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChallanDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                       ChallanDetailsController controller = ChallanDetailsController.getInstance() ;
            }
        });
    }
        
    
       private static int counter = 0,rowCounter = 0;
       public String comboDarValue[] = new String[2];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PChallan;
    private javax.swing.JButton back;
    private javax.swing.JComboBox comboDar;
    private javax.swing.JComboBox comboMoh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton print;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
